### ISSUE TITLE
Strange bug: word disappears when set_dewidow_word_number is > 1

### ISSUE THREAD

**Issue by benface** [mundschenk-at/php-typography#106]
Simplest reproducible case:

1. Set `set_dewidow_word_number` to `2`
2. Process this HTML:
    ```
    <p>
        Test
    </p>
    ```
    (Note: the newlines matter; `<p>Test</p>` doesn't reproduce the issue)
3. Notice the "Test" word is gone; the source reads: `<p></p>`

**Comment by mundschenk-at** [comment]
I'll look into it.

**Comment by benface** [comment]
Appreciate the super quick reply!

**Comment by mundschenk-at** [comment]
@benface Have you got a self-contained minimal example? I've tried reproducing this issue, but I can't seem to trigger it.

```bash
$ php --version
PHP 7.3.6 (cli) (built: Jun 17 2019 08:40:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies
$ cat foo.php
```
```php
<?php

include "vendor/autoload.php";

$typo = new \PHP_Typography\PHP_Typography();
$s    = new \PHP_Typography\Settings();

$s->set_dewidow_word_number(2);

$input = "<p>\n\tTest\n</p>";

echo $typo->process( $input, $s );
echo "\n";
```
```bash
$ php foo.php 
<p>Test&nbsp;</p>
```

**Comment by benface** [comment]
@mundschenk-at Huh. I apologize, I can't seem to be able to reproduce this anymore. Sorry for wasting your time!

**Comment by mundschenk-at** [comment]
No problem. It might have been something I fixed along the way while working on other things.
