### ISSUE TITLE
Square and cubic metre

### ISSUE THREAD

**Issue by theamnesic** [mundschenk-at/php-typography#112]
Hi!

Square and cubic metre `m2` and `m3` aren't transformed to `m²` and `m³`.

When somebody type 250m2 or 250m3, it would be a good enhancement to convert `2` and `3` to glyphs ² and ³ (and [not superscript](https://github.com/mundschenk-at/wp-typography/issues/248#issuecomment-494946380)).

Thanks!

**Comment by mundschenk-at** [comment]
Closed by #117.
