### ISSUE TITLE
Incorrect quote parsing with footnotes

### ISSUE THREAD

**Issue by mundschenk-at** [mundschenk-at/php-typography#134]
Reported as a [comment on the wp-Typography webpage](https://code.mundschenk.at/wp-typography/#comment-877): `à "l’âge" <sup><a>N112</a></sup>` is rendered `à&nbsp;«&nbsp;l’âge«&nbsp;<sup><a>N112</a></sup>`. To fix this, the algorithm would have to take the adjacent element into account, not only adjacent text.

**Comment by mundschenk-at** [comment]
Not currently reproducibly on `7.0.0-dev`, original support ticket author asked for clarification.

**Comment by belbernard** [comment]
```
Hello, look at my page https://lebonheurestpossible.org/vivre-longtemps/
Near bottom of text, occurrence  of « New-Age ». You can see that the closing quote is displayed '«' instead of '»'.
The HTML code is  "New-Age"<sup><a ... etc.
The '<' sign of "<sup>" should be identified as an end of word, just like any punctuation mark.
```

**Comment by mundschenk-at** [comment]
Thank you @belbernard for the clarification. However, that is not how the processing works. The HTML is parsed using a DOM parser and then PHP-Typography just looks at the textnodes in the DOM, not at individual characters. 

I have locally implemented support for properly recognizing `<br>` as whitespace, and stopping parsing at `<sup>` or `<sub>` nodes could be implemented as well, but when I've added these snippets to my tests, they already are parsed correctly: `'à "l’âge"<sup>N112</sup>'` results in `'&agrave; &laquo;&#8239;l&rsquo;&acirc;ge&#8239;&raquo;<sup>N112</sup>'`

**Comment by mundschenk-at** [comment]
Never mind, I think I found an issue with the tests.
