### ISSUE TITLE
Not displaying text after ,<br> 

### ISSUE THREAD

**Issue by Coysh** [mundschenk-at/php-typography#136]
### Describe the bug
I have a redactor field that has the following text in it:
`<p>Test,<br>test,</p><p>test,<br>test,<br>test,</p><p>test</p>`

In my twig file I have the following:
```
{% set paragraphs = block.text | split('</p>') %}
{% for para in paragraphs %}
	{{ para | typogrify }}
{% endfor %}

```
Output is the below:
![image](https://user-images.githubusercontent.com/5764356/87559715-8ff68e80-c6b2-11ea-9adc-5850521d16de.png)

Or as HTML
```
<p>Test,<br></p>
<p>test,<br><br></p>
<p>test</p>
```

**Comment by Coysh** [comment]
First appeared here: https://github.com/nystudio107/craft-typogrify/issues/37

**Comment by mundschenk-at** [comment]
Hi @Coysh, can you create a minimal test case that happens with the library itself? I've got no idea what the `typogrify` command actually applies (in terms of my library) and I'm not really familiar with Twig either (other than knowing it is a templating engine).

So to understand what the bug actually is, I need to know what input is passed to [`PHP_Typography::process()`](https://github.com/mundschenk-at/php-typography/blob/master/src/class-php-typography.php#L100) and what the result of that call is (and what it should be - sometimes expectations differ).

**Comment by mundschenk-at** [comment]
Have you been able to solve this issue, @Coysh?

**Comment by mundschenk-at** [comment]
Have you got a minimal example for me to investigate this, @Coysh?

**Comment by mundschenk-at** [comment]
I am assuming this is not relevant anymore, @Coysh. It looks like it might have been a HTML parser bug, but if so, it has been fixed in the meantime.
