### ISSUE TITLE
Space between every letter

### ISSUE THREAD

**Issue by GuyVervilleSpiria** [mundschenk-at/php-typography#137]
Hi, I do not understand why all the text is broken into one letter per word...

![renderedtext2](https://user-images.githubusercontent.com/69694028/115068640-85c32400-9ec0-11eb-82c6-9141f9d2feb2.png)

![renderedText](https://user-images.githubusercontent.com/69694028/115068508-590f0c80-9ec0-11eb-88c8-40a6ce43de34.png)

The code is a basic trial:
`
$settings = new \PHP_Typography\Settings();
$settings->set_hyphenation( true );
if(user()->language->name == "fr"){
    $settings->set_hyphenation_language( 'fr' );
    $settings->set_french_punctuation_spacing( true );
}else{
    $settings->set_hyphenation_language( 'en-US' );
}
$typo = new \PHP_Typography\PHP_Typography();
$test = "Ange Michael is 27-28 years old and grows cocoa. His father died of malaria in 2009. The son had to take over the hectare of cocoa trees on his own to support the family. His mother works as a housekeeper, and, year in, year out, Ange Michael manages to provide them with the bare necessities. He does not live with them, however, and has his own house. He would like to get married, has a girlfriend who is still studying, but as long as he cannot live decently, he cannot get married.";
$hyphenated_html = $typo->process( $test, $settings );

`

**Comment by mundschenk-at** [comment]
Are you, perchance using Craft? If so, it is a recurrence of #109.

**Comment by GuyVervilleSpiria** [comment]
No, I am using ProcessWire. I will try outside this CMS.

Guy Verville
SPIRIA
________________________________
De : Der Mundschenk & Compagnie ***@***.***>
Envoyé : Saturday, April 17, 2021 4:54:40 AM
À : mundschenk-at/php-typography ***@***.***>
Cc : Guy Verville ***@***.***>; Author ***@***.***>
Objet : Re: [mundschenk-at/php-typography] Space between every letter (#137)


Are you, perchance using Craft? If so, it is a recurrence of #109<https://github.com/mundschenk-at/php-typography/issues/109>.

**Comment by mundschenk-at** [comment]
> No, I am using ProcessWire. I will try outside this CMS. 

Thank you. The cause is very likely similar to the one in the referenced issue ([a `setlocale` call in an always-autoloaded boostrap file](https://github.com/mundschenk-at/php-typography/issues/109#issuecomment-491010719)).

**Comment by GuyVervilleSpiria** [comment]
I will check that. BTW, there is a port for ProcessWire, but for the original PHP Typography which inspires yours, I think. The only problem with this module is that it is still not multi-lingual and in beta.

https://gitlab.com/rockettpw/tools/typographer
https://processwire.com/talk/topic/15130-typographer/page/1/

**Comment by mundschenk-at** [comment]
@GuyVervilleSpiria Have you been able to investigate the issue or produce a minimal example for me to look at?

**Comment by GuyVervilleSpiria** [comment]
Hi,
Sorry I didn't intervene earlier. The problem is probably similar to what I experienced with the module for ProcessWire. I just clarified a few things for the French.

```wire()->addHookAfter('TextformatterTypographer::customTypographerSettings', function (HookEvent $event) {
    /** @var \PHP_Typography\Settings $settings */
    $settings = $event->return;
    $lang = $event->user->language->name;
    if ($lang === 'fr') {
        $settings->set_hyphenation_language('fr');
        $settings->set_french_punctuation_spacing(true);
    }
});```
