### ISSUE TITLE
Process is not applied

### ISSUE THREAD

**Issue by jonnitto** [mundschenk-at/php-typography#139]
If I initialize the settings with `false`, I can't enable anything. But if I initialize it without parameter, I can turn features off (e.g. `set_hyphenation(false)`

I also see no de widow, even with the default setting…

**Comment by mundschenk-at** [comment]
Do you have a minimal example somewhere (gist or repo is fine)?

**Comment by mundschenk-at** [comment]
@jonnitto Is this still relevant?
