### ISSUE TITLE
UTF-Non-breaking-Space before Endash is replaced by regular space

### ISSUE THREAD

**Issue by animaux** [mundschenk-at/php-typography#146]
php-typography seems to remove intentionally set non-breaking-spaces before en-dashes. We use them in order to prevent lines from starting with a dash, like this `[non-breaking-space][en-dash][regular-space]`.

Through php-typography:

![Bildschirmfoto 2022-03-07 um 11 30 18](https://user-images.githubusercontent.com/446874/157014408-58df4f63-ea61-4d2b-a108-e09cbf63ec3c.png)

Without php-typography (intended behaviour):

![Bildschirmfoto 2022-03-07 um 11 30 35](https://user-images.githubusercontent.com/446874/157014486-d47fc1d1-756c-45ea-90c6-cda4e56f4a52.png)

Version is 6.0 (in Craft Typogrify plugin)

**Comment by mundschenk-at** [comment]
Could you please provide a standalone test case (using just the library)?

**Comment by animaux** [comment]
Here’s a simple test-case: https://gist.github.com/animaux/ae3e2a96f886f8dedb3ca736194e84a0

Result is different than the one in the craft extension (NO-BREAK SPACE is retained), so the problem seems to be outside php-typography. Closing this, thanks!
