### ISSUE TITLE
Possible to escape selectively?

### ISSUE THREAD

**Issue by dcplebranch** [mundschenk-at/php-typography#152]
Love the library. However, I'm having an issue where the term "Open 24/7" is being typogrified into a weird fraction thingy. Is there a way to typogrify everything except this select phrase? If there is a way to escape selectively, that would also work. Just to be clear, I know how to change the settings and turn off the fraction thingy... but I would like to keep my settings the same, because MOST of the time I'd like the fraction thingy... but every once in a while (like Open 24/7) I'd like it not to happen. It would be nicest if I could specify within the string somehow, for example with a special character, that the following phrase should not be processed? Thanks,

**Comment by mundschenk-at** [comment]
Wrapping it in `<span class="noTypo">` should do the trick.

**Comment by dcplebranch** [comment]
Thanks! That worked perfectly for my needs!
