### ISSUE TITLE
Maybe not working with html heading tags?

### ISSUE THREAD

**Issue by Lennso** [mundschenk-at/php-typography#153]
See this first: https://github.com/nystudio107/craft-typogrify/issues/78

I use typogrify plugin for craft which uses php-typography:
`{{ entry.editor | typogrify }}`

My typogrify.php config:
```
"set_hyphenation" => true,
"set_hyphenate_headings" => true
```

My (german-text) html output:
```
<div>
<h6>Krank werden kann Jede:r</h6>
<h2>Warum brauche ich eine private Krankentagegeldversicherung?</h2>
<p>Die Krankentagegeld­&shy;versicherung schützt Sie gegen den Verdienstausfall bei Arbeits­&shy;unfähigkeit, soweit diese auf einer Krankheit oder einem Unfall beruht. Die Versicherung zahlt ab vereinbartem </p>
</div>
```

Hyphenation for my p-element is working, but not for the headings. Could it have something to do with this package?

**Comment by mundschenk-at** [comment]
I'd need your full configuration to be sure, but most likely you have either enabled dewidowing or are skipping the contents of `<h1>` and `<h2>`.

**Comment by mundschenk-at** [comment]
Is this still relevant, @Lennso?

**Comment by u07** [comment]
> I'd need your full configuration to be sure, but most likely you have either enabled dewidowing or are skipping the contents of `<h1>` and `<h2>`.

Sorry to interfere, but how do you do that skipping of tags? I'd like to skip <script> tags. I'm using [this plugin](https://github.com/bricebou/grav-plugin-better-typography) and it just ruins JS :)

**Comment by mundschenk-at** [comment]
Apparently not.
