### ISSUE TITLE
Not all settings are taken into account for the settings hash 

### ISSUE THREAD

**Issue by shimikano** [mundschenk-at/php-typography#27]
`$settings->get_hash()` only considers the `$data` member of the `Settings` class, but not other relevant members such as `$no_break_narrow_space`, `$primary_quote_style`, `$dash_style`, etc.

This results in a hash collision for two `Settings` instances that, e.g., only differ in the dash style.

In my client code, I quick-fixed this by using
```php
md5(print_r($settings, true))
```
as hash.

**Comment by mundschenk-at** [comment]
You are right, the recent changes fail to take that into account. Will be fixed in the next version.
