### ISSUE TITLE
Dewidowing seems to override unit spacing

### ISSUE THREAD

**Issue by mikerockett** [mundschenk-at/php-typography#34]
When dewidowing, unit spaces don’t appear to be affected when at the end of a paragraph. As such `1 KB` will be converted to `1&nbsp;KB`, even when unit spacing is turned on. Expected result is `1KB`.

**Comment by mundschenk-at** [comment]
Unit spacing will never produce `1KB`. Depending in the setting for the narrow no-break space character, it will either produce `1&nbsp;KB` or `1&#8239;KB`. Or do you mean the latter is replaced by the former when dewidowing is enabled?

**Comment by mikerockett** [comment]
Apologies - that's really just for the purposes of presentation... You are correct.

Yes, so when dewidowing is enabled, the result is always `1&nbsp;KB`, irrespective of both the unit spacing and the narrow space setting.

**Comment by mundschenk-at** [comment]
@mikerockett You are right, I've just looked at the code and the narrow no-break space is not properly escaped during dewidowing.
