### ISSUE TITLE
Add Release Roadmap

### ISSUE THREAD

**Issue by khalwat** [mundschenk-at/php-typography#60]
First, thank you for your work, I very much appreciate your contributions.

I have a small suggestion about the verisoning that you're doing; typically we'll have something like this in our `composer.json`:

```
    "require": {
        "mundschenk-at/php-typography": "^5.0"
    },
```

So whenever you update the major version number (as recently happened to `6.0`), that means that we will no longer receive updates.

This can be further complicated if we have a larger project where there are components or plugins that may also require the library, and thus become incompatible when one asks for `^5.0` and the other `^6.0`

So it might be helpful if the major version in the semver is only changed when there are very large, breaking changes in the library. So for instance, if php-typography stayed at `6.x.x` for a very long time (until there were major breaking changes to the API or major breaking architectural changes), that'd probably be ideal from an application developer's POV.

Just my two cents!

**Comment by mundschenk-at** [comment]
I'll try to be more considerate of other users of `php-typography` in the future. The thing is, while 5.0 made the library much more modular, there are still some problematic aspects of the API (now mostly the settings object). I'd like to rework that, but it will be a breaking change. 

Technically, 6.0.0 contained some breaking changes (removed deprecated properties and a changed constructor for `PHP_Typography`), even though the API mostly staid intact. According to semver, that's a new major version.

But of course you are right, now that other people have started using the library, there should be some advance warning about breaking changes/major versions, maybe a kind of roadmap etc.
