### ISSUE TITLE
HTML special chars processing

### ISSUE THREAD

**Issue by brutto** [mundschenk-at/php-typography#89]
Thanks for this powerfull library. Found strange behaviour of this typo

### Settings

```php
        $typoSettings = new Settings(false);

        $typoSettings->set_space_collapse();
        $typoSettings->set_smart_marks();
        $typoSettings->set_single_character_word_spacing();
        $typoSettings->set_unit_spacing();
        $typoSettings->set_numbered_abbreviation_spacing();

        $typoSettings->set_smart_quotes();
        $typoSettings->set_smart_quotes_primary();
        $typoSettings->set_smart_quotes_secondary();
```

### Predictable (Correct)
```
input: He is robot, am i&nbsp;too?

process input (htmlentity()): He is robot, am i&amp;nbsp;too?

typo output: He is robot, am i&amp;nbsp;too?
```
Output string will we as input with `&nbsp;` as a text.

### Unpredictable (Incorrect)
```
input: He is a robot, am i&nbsp;too?

process input: He is a robot, am i&amp;nbsp;too?

typo: He is a&nbsp;robot, am i&nbsp;too?
```
Output string will we without `&nbsp;` as a text, all become spaces.

PS: the same with `& <=> &amp;`

**Comment by mundschenk-at** [comment]
I'm not completely sure I understand the issue correctly. Just to clarify, the input string is not escaped by PHP-Typography, so `&nbsp;` is processed as a `NO-BREAK SPACE` literal. The `$html` input parameter of the `PHP_Typography::process` method is assumed to be a valid HTML fragment (i.e. without the document type, and surrounding `<html>` and `<body>` tags, but otherwise well-formed).

**Comment by brutto** [comment]
@mundschenk-at 

This is working code about second variant:
```php
$string = 'He is a robot, am i&nbsp;too?'; // <-- input
$string = htmlspecialchars($string); // <-- process innput
$string = PHP_Typography::process($string); // <-- typo
var_dump($string);
```
Expected `$string` will be: 
`He is a&nbsp;robot, am i&amp;nbsp;too?`, 

But in real we have:
 `He is a&nbsp;robot, am i&nbsp;too?`. 

Second `&amp;nbsp;` become `&nbsp;`.

Im not dig deeper, but first impression this behaviour not correct. Am i right?

**Comment by mundschenk-at** [comment]
OK, I see what you mean. Yes, the result should be `He is a&nbsp;robot, am i&amp;nbsp;too?` in this case. I'll investigate the issue.
