### ISSUE TITLE
Keep units together (€)

### ISSUE THREAD

**Issue by strarsis** [mundschenk-at/php-typography#93]
## Issue Overview
Units should be kept together, '€' had been added to the list of units.

## Steps to Reproduce (for bugs)
1. Have text on page that contains a price with a currency like "10 €" where its container should cause word breaking/hyphenation.
2. Notice that still a break occurs between the number (here "10") and the currency symbol (here "€").
The value and currency symbol are not wrapped into a wrapper element.
3. Adding the "€" to the list of units in wp-typography settings doesn't seem to prevent breaking.

WordPress 4.9.8, wp-typography 5.4.2, Gutenberg editor page.
Recent Chrome on Windows 10 Pro x64.

## Expected Behavior
No breaking between value and unit symbol.

## Current Behavior
Prices with currency symbol (e.g. "10 €") are apparently not handled.

**Comment by mundschenk-at** [comment]
Uh-oh. There were _a  lot_ of issues with the unit spacing routines. Thanks for the report!

**Comment by strarsis** [comment]
@mundschenk-at: It would be great if php-typography dependency could also be updated in wp-typography plugin and published.

**Comment by mundschenk-at** [comment]
Yes, of course, in due time :)
